### PR TITLE
Fix RuntimeHelpers.IsReferenceOrContainsReferences polyfill

### LINKED ISSUE #32: Fix portable IsReferenceOrContainsReference<T> for pointer types
## Overview

The `IsReferenceOrContainsReferences(Type)` method we use to polyfill on .NET Standard < 2.1 has a bug that was inherited from the portable implementation originally in the BCL, which causes pointer types or types containing pointer types to be reported as being reference types. This is caused by `Type.IsValueType` actually returning `false` in this case (for... Reasons? 🤷).

https://github.com/CommunityToolkit/dotnet/blob/1a94430894333ca559b88f32665e6b82f36ebc87/CommunityToolkit.HighPerformance/Helpers/Internals/RuntimeHelpers.cs#L184

There should be an additional check for pointer types, and also a workaround for `IsValueType`.

### PR DESCRIPTION
**Pull request by Sergio0694**
**Closes #32**

This PR fixes the internal `RuntimeHelpers.IsReferenceOrContainsReferences<T>` polyfill for pointer types.

### CODE REVIEW

**Review by Arlodotexe — APPROVED** [review]

File: tests/CommunityToolkit.HighPerformance.UnitTests/Helpers/Internals/Test_RuntimeHelpers.cs [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+
+    private struct UnmanagedStruct2
+    {
+        public int A;
+        public UnmanagedStruct1 B;
+        public UnmanagedStruct1? C;
+        public Guid? D;
+    }
+
+    private struct GenericStruct<T>
```
Comment (XAML-Knight) [inline tests/CommunityToolkit.HighPerformance.UnitTests/Helpers/Internals/Test_RuntimeHelpers.cs:79]: I tested an extra assertion, and this passed, as well: 

`Assert.IsFalse(RuntimeHelpers.IsReferenceOrContainsReferences<GenericStruct<UnmanagedStruct1>>());`

**Review by XAML-Knight — APPROVED** [review]

File: tests/CommunityToolkit.HighPerformance.UnitTests/Helpers/Internals/Test_RuntimeHelpers.cs (hunk 1 above)
Comment (Sergio0694) [reply tests/CommunityToolkit.HighPerformance.UnitTests/Helpers/Internals/Test_RuntimeHelpers.cs:81]: Added this test as well for good measure, why not! 😄
