### PR TITLE
Change IndexOf APIs to return -1 if not found

### LINKED ISSUE #189: Change `IndexOf<T>([ReadOnly]Span<T>, ref/in T)` to return `-1` instead of throwing
### Overview

Currently, the [by-ref `IndexOf`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.highperformance.readonlyspanextensions.indexof) extensions for `[ReadOnly]Span<T>` throw when the supplied value does not lie within the span. This is not very intuitive, one would normally expect the API to return `-1` in this scenario (especially given that the returned index is a signed integer.)

### API breakdown

```diff
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static int IndexOf<T>(this Span<T> span, ref T value)
{
    ref T r0 = ref MemoryMarshal.GetReference(span);
    IntPtr byteOffset = Unsafe.ByteOffset(ref r0, ref value);

    nint elementOffset = byteOffset / (nint)(uint)Unsafe.SizeOf<T>();

    if ((nuint)elementOffset >= (uint)span.Length)
    {
-        ThrowArgumentOutOfRangeExceptionForInvalidReference();
+        return -1;
    }

    return (int)elementOffset;
}
```
```diff
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static int IndexOf<T>(this ReadOnlySpan<T> span, in T value)
{
    ref T r0 = ref MemoryMarshal.GetReference(span);
    ref T r1 = ref Unsafe.AsRef(value);
    IntPtr byteOffset = Unsafe.ByteOffset(ref r0, ref r1);

    nint elementOffset = byteOffset / (nint)(uint)Unsafe.SizeOf<T>();

    if ((nuint)elementOffset >= (uint)span.Length)
    {
-        SpanExtensions.ThrowArgumentOutOfRangeExceptionForInvalidReference();
+        return -1;
    }

    return (int)elementOffset;
}
```

### Usage example

```cs
int index = span.IndexOf(ref value);

if (index == -1)
{
    // value does not exist
}

// value exists
```

### Breaking change?

Yes

### Alternatives

Alternatively, a non-throwing variant of the API could be provided.

### Additional context

_No response_

### Help us help you

No, just wanted to propose this

### PR DESCRIPTION
**Pull request by Sergio0694**
**Closes #189**

## PR Checklist

- [X] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [X] Based off latest main branch of toolkit
- [X] PR doesn't include merge commits (always rebase on top of our main, if needed)
- [X] Tested code with current [supported SDKs](../#supported)entire description over that)
- [X] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [X] Header has been added to all new source files (run _build/UpdateHeaders.bat_)
- [ ] Contains **NO** breaking changes
- [X] Every new API (including internal ones) has full XML docs
- [X] Code follows all style conventions

### CODE REVIEW

File: CommunityToolkit.HighPerformance/Extensions/ReadOnlySpanExtensions.cs [hunk 1]
```diff
@@ -208,7 +208,7 @@ public static ReadOnlySpan2D<T> AsSpan2D<T>(this ReadOnlySpan<T> span, int offse
     /// <typeparam name="T">The type if items in the input <see cref="ReadOnlySpan{T}"/>.</typeparam>
     /// <param name="span">The input <see cref="ReadOnlySpan{T}"/> to calculate the index for.</param>
     /// <param name="value">The reference to the target item to get the index for.</param>
-    /// <returns>The index of <paramref name="value"/> within <paramref name="span"/>.</returns>
+    /// <returns>The index of <paramref name="value"/> within <paramref name="span"/>, or <c>-1</c>.</returns>
     /// <exception cref="ArgumentOutOfRangeException">Thrown if <paramref name="value"/> does not belong to <paramref name="span"/>.</exception>
```
Comment (powerdude) [inline CommunityToolkit.HighPerformance/Extensions/ReadOnlySpanExtensions.cs:212]: shouldn't this be removed too?

Comment (Sergio0694) [reply CommunityToolkit.HighPerformance/Extensions/ReadOnlySpanExtensions.cs]: Whoops! Fixed in https://github.com/CommunityToolkit/dotnet/pull/190/commits/76f339fa8805af02092496bff65492c16d4a2342, thanks! 😄

**Review by Arlodotexe — APPROVED** [review]
